
/*
    
    1 PONTO NA PS GARANTINDO
    
    EXERCICIO 10 - SOLUÇÃO

*/


SELECT COUNT(*) TOTAL, 
 (SELECT COUNT(*) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'rrrr') = '1995') AS "1995", 
 (SELECT COUNT(*) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'rrrr') = '1996') AS "1996", 
 (SELECT COUNT(*) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'rrrr') = '1997') AS "1997", 
 (SELECT COUNT(*) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'rrrr') = '1998') AS "1998" 
FROM EMPLOYEES group by 1;


/* RESOLVENDO COM DECODE */

SELECT COUNT(*) TOTAL, 
 SUM(DECODE(TO_CHAR(HIRE_DATE, 'rrrr'), 1995, 1, 0)) "1995",
 SUM(DECODE(TO_CHAR(HIRE_DATE, 'rrrr'), 1996, 1, 0)) "1996",
 SUM(DECODE(TO_CHAR(HIRE_DATE, 'rrrr'), 1997, 1, 0)) "1997",
 SUM(DECODE(TO_CHAR(HIRE_DATE, 'rrrr'), 1998, 1, 0)) "1998" 
FROM EMPLOYEES;


